### ISSUE TITLE
Anonymous Admin Support

### ISSUE THREAD

**Issue by jk6521** [Black-Bulls-Bots/Natsuki#3]
## Anonymous admin support for admin commands
bot will send a button to verify which admin user is using the command to log their actions and check their permission for needed commands.

- [x] promote
- [x] demote
- [x] pin
- [x] unpin
- [x] unpinll
- [x] title
- [x] ban
- [x] unban
- [ ] gban
- [ ] admincache
- [ ] antifloods
- [ ] antispam
- [ ] purges

**Comment by jaiboiyt** [comment]
@jk6521 Okie

**Comment by jk6521** [comment]
ban and unban done #5

**Comment by jk6521** [comment]
Archiving this repo
